name: Generate Snake Animation
on:
  schedule:
    - cron: "0 */12 * * *" # هر 12 ساعت اجرا می‌شود
  workflow_dispatch: # امکان اجرای دستی

permissions:
  contents: write # دسترسی نوشتن ضروری است

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Game
        uses: Platane/snk@v3[citation:3]
        with:
          github_user_name: najmeRajabi # نام کاربری خود را اینجا وارد کنید
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v4[citation:8]
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
